stages:
  - test

test:
  stage: test
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - export DATABASE_URL=postgres://ergo:ergo:5432/ergo
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install -r requirements.txt
  - cp ErgoApi/production.py.sample ErgoApi/production.py
  - python3 manage.py test
