# Generated by Django 2.2 on 2019-12-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20191203_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='tx_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
