# Generated by Django 2.2 on 2019-12-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20191207_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('POOL_DIFFICULTY_FACTOR', 'POOL_DIFFICULTY_FACTOR'), ('REWARD', 'REWARD'), ('REWARD_FACTOR', 'REWARD_FACTOR')], max_length=255)),
                ('value', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
