# Generated by Django 2.2.9 on 2020-01-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20191208_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='key',
            field=models.CharField(choices=[('POOL_BASE_FACTOR', 'Pool base factor'), ('REWARD', 'Reward'), ('REWARD_FACTOR', 'Reward factor'), ('SHARE_CHUNK_SIZE', 'Share chunk size')], max_length=255),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
