# Generated by Django 2.2.9 on 2020-02-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_auto_20200118_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuration',
        ),
    ]
