# Generated by Django 2.2.14 on 2020-10-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_delete_configuration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
    ]
